[workspace]
name = "opendtect_apps"
channels = ["conda-forge", "nvidia"]
platforms = [
    {platform = "linux-64", cuda = "12"},
    {platform = "win-64", cuda = "12"}
]
preview = ["pixi-build"]

[activation.env]
ODPYTHON = "/opt/seismic/OpendTectPro_rc/0.0.0"
PYTHONPATH = "${PIXI_PROJECT_ROOT}/src:$ODPYTHON/bin/python"

[dependencies]
python = "<3.13"
cuda-version = "12.*"
numpy = ">=2.5.0,<3"
pyside6 = "==6.9.3"
pytorch-gpu = "*"
torchvision = "*"
xarray = ">=2026.4.0,<2027"

[target.linux-64.dependencies]
qt6-wayland = "==6.9.3"

[tasks]
zipmodel = "python src/zipmodel_runner"
