[workspace]
name = "opendtect_apps"
channels = ["conda-forge", "nvidia"]
platforms = [
    {platform = "linux-64", cuda = "12"},
    {platform = "win-64"}
]
preview = ["pixi-build"]

[activation.env]
#ODPYTHON = "/opt/seismic/OpendTectPro_rc/0.0.0"
ODPYTHON = "/home/wayne/Development/dGB/odmain/OpendTect/inst"
DGBPYTHON = "/home/wayne/Development/dGB/dgbpy-dev/dgbpy-main"
PYTHONPATH = "${PIXI_PROJECT_ROOT}/src:$ODPYTHON/bin/python:$DGBPYTHON"

[dependencies]
python = "<3.13"
cuda-version = "12.*"
marimo = "*"
numpy = ">=2.5.0,<3"
pyside6 = "==6.9.3"
torchvision = "*"
xarray = ">=2026.4.0,<2027"
matplotlib = ">=3.10.9,<4"
pyqtgraph = ">=0.14.0,<0.15"

[target.linux-64.dependencies]
pytorch-gpu = "*"
qt6-wayland = "==6.9.3"

[target.win-64.dependencies]
pytorch-cpu = "*"

[tasks]
viewer = "python src/slice_viewer"
zipmodel = "python src/zipmodel_runner"
